package MyApp;

import javax.swing.table.*;

import java.awt.*;
import java.util.ArrayList;

import javax.swing.*;    

import MyLibs.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jack
 */
public class MainFrame extends javax.swing.JFrame {
        Block block1 = new Block("Block 1", 1);
        Block block2 = new Block("Block 2", 2);
        Block block3 = new Block("Block 3", 3);
        Block block4 = new Block("Block 4", 4);
        Block block5 = new Block("Block 5", 5);

        String[] blockList = {"Block 1", "Block 2", "Block 3", "Block 4", "Block 5"};

        StatusFactory statusFactory = new StatusFactory();
        LotFactory lotFactory = new LotFactory();

        

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle("Real-Estate Sales and Management System");
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        ManagementTablePane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LotTable = new javax.swing.JTable();
        MainManagementPane = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ManagementSearchPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        AddLotButton = new javax.swing.JButton();
        EditLotButton = new javax.swing.JButton();
        DeleteLotButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ReportPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        numBlocks = new javax.swing.JLabel();
        numBlocksReport = new javax.swing.JLabel();
        numTotalLots = new javax.swing.JLabel();
        block1Lots = new javax.swing.JLabel();
        block2Lots = new javax.swing.JLabel();
        block3Lots = new javax.swing.JLabel();
        block4Lots = new javax.swing.JLabel();
        block5Lots = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        LotTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot Number", "Block Number", "Lot Size", "Lot Price", "Lot Status"
            }
        ));
        LotTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(LotTable);
        if (LotTable.getColumnModel().getColumnCount() > 0) {
            LotTable.getColumnModel().getColumn(0).setResizable(false);
            LotTable.getColumnModel().getColumn(1).setResizable(false);
            LotTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout ManagementTablePaneLayout = new javax.swing.GroupLayout(ManagementTablePane);
        ManagementTablePane.setLayout(ManagementTablePaneLayout);
        ManagementTablePaneLayout.setHorizontalGroup(
            ManagementTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagementTablePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE))
        );
        ManagementTablePaneLayout.setVerticalGroup(
            ManagementTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagementTablePaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Mark as Reserved");

        jLabel2.setText("Location (Block)");

        jTextField2.setText("3");

        jLabel3.setText("Price (PHP)");

        jButton1.setText("Search");

        jLabel1.setText("Size (m^2)");

        jCheckBox1.setText("Sold/Reserved");

        jTextField1.setText("100");

        jTextField3.setText("600000");

        javax.swing.GroupLayout ManagementSearchPaneLayout = new javax.swing.GroupLayout(ManagementSearchPane);
        ManagementSearchPane.setLayout(ManagementSearchPaneLayout);
        ManagementSearchPaneLayout.setHorizontalGroup(
            ManagementSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagementSearchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManagementSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ManagementSearchPaneLayout.createSequentialGroup()
                        .addGroup(ManagementSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ManagementSearchPaneLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ManagementSearchPaneLayout.setVerticalGroup(
            ManagementSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagementSearchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManagementSearchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ManagementSearchPane, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        AddLotButton.setText("Add Lot");
        AddLotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLotButtonActionPerformed(evt);
            }
        });

        EditLotButton.setText("Edit Lot");
        EditLotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditLotButtonActionPerformed(evt);
            }
        });

        DeleteLotButton.setText("Delete Lot");
        DeleteLotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLotButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Mark as Sold");

        jButton7.setText("Mark for Sale");

        javax.swing.GroupLayout MainManagementPaneLayout = new javax.swing.GroupLayout(MainManagementPane);
        MainManagementPane.setLayout(MainManagementPaneLayout);
        MainManagementPaneLayout.setHorizontalGroup(
            MainManagementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainManagementPaneLayout.createSequentialGroup()
                .addGroup(MainManagementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainManagementPaneLayout.createSequentialGroup()
                        .addGroup(MainManagementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainManagementPaneLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(DeleteLotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MainManagementPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MainManagementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MainManagementPaneLayout.createSequentialGroup()
                                .addComponent(AddLotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditLotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(34, 34, 34))
        );
        MainManagementPaneLayout.setVerticalGroup(
            MainManagementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainManagementPaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(MainManagementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLotButton)
                    .addComponent(EditLotButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteLotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(2, 2, 2)
                .addComponent(jButton3)
                .addGap(3, 3, 3)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainManagementPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManagementTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainManagementPane, javax.swing.GroupLayout.PREFERRED_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(ManagementTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Management", jPanel4);

        ReportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportPanelMouseClicked(evt);
            }
        });

        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot Number", "Block Number", "Lot Size", "Lot Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(ReportTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Report");

        numBlocks.setText("Number of Blocks : ");

        numTotalLots.setText("Number of Total Lots : ");

        block1Lots.setText("Block 1: ");

        block2Lots.setText("Block 2: ");

        block3Lots.setText("Block 3: ");

        block4Lots.setText("Block 4: ");

        block5Lots.setText("Block 5: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numBlocks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numBlocksReport))
                    .addComponent(numTotalLots)
                    .addComponent(block3Lots)
                    .addComponent(block4Lots)
                    .addComponent(block5Lots)
                    .addComponent(block2Lots)
                    .addComponent(block1Lots))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numBlocks)
                    .addComponent(numBlocksReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numTotalLots)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(block1Lots)
                .addGap(6, 6, 6)
                .addComponent(block2Lots)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(block3Lots)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(block4Lots)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(block5Lots)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReportPanelLayout = new javax.swing.GroupLayout(ReportPanel);
        ReportPanel.setLayout(ReportPanelLayout);
        ReportPanelLayout.setHorizontalGroup(
            ReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ReportPanelLayout.setVerticalGroup(
            ReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Report", ReportPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1496, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void AddLotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLotButtonActionPerformed
    JFrame addLotFrame = new JFrame("Add Lot");
    addLotFrame.setSize(500, 300);
    addLotFrame.setLayout(new GridLayout(6, 2));
    
    // Labels
    JLabel lotNumberLabel = new JLabel("Lot Number:");
    JLabel blockNumberLabel = new JLabel("Block Number:");
    JLabel lotSizeLabel = new JLabel("Lot Size:");
    JLabel lotPriceLabel = new JLabel("Lot Price:");
    JLabel lotStatusLabel = new JLabel("Lot Status:");
    
    // Text fields
    JTextField lotNumberField = new JTextField();
    JTextField lotSizeField = new JTextField();
    JTextField lotPriceField = new JTextField();

    JComboBox<String> blockNumberField = new JComboBox<>(blockList);

    String[] statusChoices = {"For Sale", "Reserved", "Sold"};
    JComboBox<String> lotStatusField = new JComboBox<String>(statusChoices);
    
    // Add components to frame
    addLotFrame.add(lotNumberLabel);
    addLotFrame.add(lotNumberField);
    addLotFrame.add(blockNumberLabel);
    addLotFrame.add(blockNumberField);
    addLotFrame.add(lotSizeLabel);
    addLotFrame.add(lotSizeField);
    addLotFrame.add(lotPriceLabel);
    addLotFrame.add(lotPriceField);
    addLotFrame.add(lotStatusLabel);
    addLotFrame.add(lotStatusField);
    
    JButton submitButton = new JButton("Submit");
    addLotFrame.add(submitButton);
        
        // Action listener for submit button
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Retrieve input values
                String lotNumber = lotNumberField.getText();
                Block blockNum = getBlock(blockNumberField.getSelectedIndex());
                String lotSize = lotSizeField.getText();
                String lotPrice = lotPriceField.getText();
                int lotStatus = lotStatusField.getSelectedIndex();
                
                try {
                    double parsedLotSize = Double.parseDouble(lotSize);
                    double parsedLotPrice = Double.parseDouble(lotPrice);
                    Status parsedLotStatus = statusFactory.createStatus(lotStatus);

                    Lot lotObject = lotFactory.createLot(parsedLotPrice);
                    lotObject.setLotNumber(lotNumber);
                    lotObject.setBlockNum(blockNum);
                    lotObject.setLotNumber(lotNumber);
                    lotObject.setLotSize(parsedLotSize);
                    lotObject.setLotPrice(parsedLotPrice);
                    lotObject.setLotStatus(parsedLotStatus);

                    if (!blockNum.checkDuplicateLot(lotObject)) {
                        JOptionPane.showMessageDialog(addLotFrame, "Duplicate lot. Enter another lot number.");
                        return;
                    } else {blockNum.assignLot(lotObject);}

                    
                    Object[] rowData = {lotNumber, blockNum, parsedLotSize, parsedLotPrice, parsedLotStatus};
                    DefaultTableModel model = (DefaultTableModel) LotTable.getModel();
                    model.addRow(rowData);
                    
            } catch (Exception e) {
                System.out.println("Error:" + e);
            }
            
            // Close the frame after submission
            addLotFrame.dispose();
        }
    
    });
    
    addLotFrame.setVisible(true);
}//GEN-LAST:event_AddLotButtonActionPerformed

    // TO-DO: CONFIRMATION MESSAGE BEFORE DELETING
    private void DeleteLotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLotButtonActionPerformed
        int lotRow = LotTable.getSelectedRow();
        String lotNumber = (String) LotTable.getValueAt(lotRow, 0);
        Block blockNumber = (Block) LotTable.getValueAt(lotRow, 1);

        System.out.println("Block Number: " + blockNumber);
        System.out.println("LotNumber: " + lotNumber);

        ArrayList<Lot> lots = blockNumber.getLots();
        for (int i=0; i<lots.size(); i++) {
            if (lots.get(i).getLotNumber() == lotNumber) {
                lots.remove(i);
            }
        }

        DefaultTableModel model = (DefaultTableModel) LotTable.getModel();
        model.removeRow(lotRow);

    }//GEN-LAST:event_DeleteLotButtonActionPerformed

    private void EditLotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLotButtonActionPerformed
        Object[] rowData = new Object[LotTable.getColumnCount()];
        int lotRow = LotTable.getSelectedRow();
        for (int i=0; i<LotTable.getColumnCount(); i++) {
            rowData[i] = LotTable.getValueAt(lotRow, i);
        }
        JFrame editLotFrame = new JFrame("Edit Lot");
    editLotFrame.setSize(500, 300);
    editLotFrame.setLayout(new GridLayout(6, 2));
    
    // Labels
    JLabel lotNumberLabel = new JLabel("Lot Number:");
    JLabel blockNumberLabel = new JLabel("Block Number:");
    JLabel lotSizeLabel = new JLabel("Lot Size:");
    JLabel lotPriceLabel = new JLabel("Lot Price:");
    JLabel lotStatusLabel = new JLabel("Lot Status:");
    
    // Text fields
    JTextField lotNumberField = new JTextField(rowData[0].toString());
    JTextField lotSizeField = new JTextField(rowData[2].toString());
    JTextField lotPriceField = new JTextField(rowData[3].toString());
    

    JComboBox<String> blockNumberField = new JComboBox<>(blockList);
    blockNumberField.setSelectedItem(rowData[1]);

    String[] statusChoices = {"For Sale", "Reserved", "Sold"};
    JComboBox<String> lotStatusField = new JComboBox<String>(statusChoices);
    lotStatusField.setSelectedItem(rowData[4]);


    // Add components to frame
    editLotFrame.add(lotNumberLabel);
    editLotFrame.add(lotNumberField);
    editLotFrame.add(blockNumberLabel);
    editLotFrame.add(blockNumberField);
    editLotFrame.add(lotSizeLabel);
    editLotFrame.add(lotSizeField);
    editLotFrame.add(lotPriceLabel);
    editLotFrame.add(lotPriceField);
    editLotFrame.add(lotStatusLabel);
    editLotFrame.add(lotStatusField);
    
    JButton submitButton = new JButton("Submit");
    editLotFrame.add(submitButton);
        
        // Action listener for submit button
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Retrieve input values
                String lotNumber = lotNumberField.getText();
                Block blockNum = getBlock(blockNumberField.getSelectedIndex());
                String lotSize = lotSizeField.getText();
                String lotPrice = lotPriceField.getText();
                int lotStatus = lotStatusField.getSelectedIndex();
                
                try {
                    double parsedLotSize = Double.parseDouble(lotSize);
                    double parsedLotPrice = Double.parseDouble(lotPrice);
                    Status parsedLotStatus = statusFactory.createStatus(lotStatus);
                    

                    for (Lot lot : blockNum.getLots()) {
                        if (lot.getLotNumber() == rowData[0]) {
                            lot.setLotNumber(lotNumber);
                            if (!blockNum.checkDuplicateLot(lot)) {
                                JOptionPane.showMessageDialog(editLotFrame, "Duplicate lot. Enter another lot number.");
                                return;
                            } else {
                                lot.setBlockNum(blockNum);
                                lot.setLotNumber(lotNumber);
                                lot.setLotSize(parsedLotSize);
                                lot.setLotPrice(parsedLotPrice);
                                lot.setLotStatus(parsedLotStatus);
                            }

                        }
                    }
                    
                    
                    DefaultTableModel model = (DefaultTableModel) LotTable.getModel();
                    model.setValueAt(lotNumber, lotRow, 0);
                    model.setValueAt(blockNum, lotRow, 1);
                    model.setValueAt(parsedLotSize, lotRow, 2);
                    model.setValueAt(parsedLotPrice, lotRow, 3);
                    model.setValueAt(parsedLotStatus, lotRow, 4);
                    
            } catch (Exception e) {
                System.out.println("Error:" + e);
            }
            
            // Close the frame after submission
            editLotFrame.dispose();
        }
    
    });
    
    editLotFrame.setVisible(true);

    }//GEN-LAST:event_EditLotButtonActionPerformed

 private void ReportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportPanelMouseClicked
    System.out.println("CALLED REPORT MOUSE CLICK");
    Block[] blocks = {block1, block2, block3, block4, block5};
    DefaultTableModel reportTableModel = (DefaultTableModel) ReportTable.getModel();
    reportTableModel.setRowCount(0); // Clear existing rows

    ArrayList<Object[]> lotDataList = new ArrayList<>();

    for (Block block : blocks) {
        for (Lot lot : block.getLots()) {
            Object[] rowData = {
                lot.getLotNumber(),
                block.getBlockNum(),
                lot.getLotSize(),
                lot.getLotPrice(),
                lot.getLotStatus()
            };
            reportTableModel.addRow(rowData);
        }
    }

    // Convert list to array and add to the table model in a single operation
    for (Object[] row : lotDataList) {
        reportTableModel.addRow(row);
    }
}//GEN-LAST:event_ReportPanelMouseClicked

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {                                                                               
            JTabbedPane pane = (JTabbedPane) evt.getSource();
            int selectedIndex = pane.getSelectedIndex();
            
            if (selectedIndex == 1) {
                populateReportTable();
                populateReportStats();
            }                    
    }
        // Method to populate the report table
        private void populateReportTable() {
            Block[] blocks = {block1, block2, block3, block4, block5};
            DefaultTableModel reportTableModel = (DefaultTableModel) ReportTable.getModel();
            reportTableModel.setRowCount(0); // Clear existing rows

            for (Block block : blocks) {
                for (Lot lot : block.getLots()) {
                    Object[] rowData = {
                        lot.getLotNumber(),
                        block.getBlockNum(),
                        lot.getLotSize(),
                        lot.getLotPrice(),
                        lot.getLotStatus()
                    };
                    reportTableModel.addRow(rowData);
                }
            }
        }

        private void populateReportStats() {
            numBlocks.setText("Number of Blocks: " + blockList.length);
            numTotalLots.setText("Number of Total Lots: " + Block.allLots.size());
            block1Lots.setText("Block 1: " + block1.getLots().size());
            block2Lots.setText("Block 2: " + block2.getLots().size());
            block3Lots.setText("Block 3: " + block3.getLots().size());
            block4Lots.setText("Block 4: " + block4.getLots().size());
            block5Lots.setText("Block 5: " + block5.getLots().size());
        }
                                       


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLotButton;
    private javax.swing.JButton DeleteLotButton;
    private javax.swing.JButton EditLotButton;
    private javax.swing.JTable LotTable;
    private javax.swing.JPanel MainManagementPane;
    private javax.swing.JPanel ManagementSearchPane;
    private javax.swing.JPanel ManagementTablePane;
    private javax.swing.JPanel ReportPanel;
    private javax.swing.JTable ReportTable;
    private javax.swing.JLabel block1Lots;
    private javax.swing.JLabel block2Lots;
    private javax.swing.JLabel block3Lots;
    private javax.swing.JLabel block4Lots;
    private javax.swing.JLabel block5Lots;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel numBlocks;
    private javax.swing.JLabel numBlocksReport;
    private javax.swing.JLabel numTotalLots;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables


    // USER-DEFINED
    public Block getBlock(int comboIndex) {
        switch (comboIndex) {
            case 0: return block1;
            case 1: return block2;
            case 3: return block3;
            case 4: return block4;
            case 5: return block5;
            default: throw new IllegalArgumentException("Invalid index");
        }
    }
}
